### ISSUE TITLE
Android 4.0.3如何支持呢？

### ISSUE THREAD

**Issue by heny2007** [EasyDSS/EasyPusher-Android#4]
07-16 12:07:30.405 30202-8662/org.easydarwin.easypusher W/dalvikvm: threadid=11: thread exiting with uncaught exception (group=0x40a6e1f8)
07-16 12:07:30.410 30202-8662/org.easydarwin.easypusher E/AndroidRuntime: FATAL EXCEPTION: CAMERA
                                                                          java.lang.NoClassDefFoundError: android.media.MediaCodecList
                                                                              at org.easydarwin.hw.CodecManager.findEncodersForMimeType(CodecManager.java:68)
                                                                              at org.easydarwin.hw.EncoderDebugger.debug(EncoderDebugger.java:230)
                                                                              at org.easydarwin.hw.EncoderDebugger.debug(EncoderDebugger.java:133)
                                                                              at org.easydarwin.hw.EncoderDebugger.debug(EncoderDebugger.java:128)
                                                                              at org.easydarwin.push.HWConsumer.startMediaCodec(HWConsumer.java:224)
                                                                              at org.easydarwin.push.HWConsumer.onVideoStart(HWConsumer.java:53)
                                                                              at org.easydarwin.push.MediaStream.startPreview(MediaStream.java:349)
                                                                              at org.easydarwin.push.MediaStream$5.run(MediaStream.java:287)
                                                                              at android.os.Handler.handleCallback(Handler.java:605)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                              at org.easydarwin.push.MediaStream$1.run(MediaStream.java:86)
07-16 12:07:30.535 30202-30202/org.easydarwin.easypusher D/OpenGLRenderer: Flushing caches (mode 0)

**Comment by milkywayriver** [comment]
使用软编码模式.
